import { join, resolve, relative, dirname } from "path";

// This plugin modifies the require-ensure code generated by Webpack
// to work with Next.js SSR
export default class NextJsSsrImportPlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap("DynamicImportPlugin", (compilation) => {
      compilation.mainTemplate.hooks.requireEnsure.tap(
        "DynamicImport",
        (code, chunk) => {
          let updatedCode = `
          if(installedChunks[chunkId] !== 0) {
              var chunk;

              if(!chunkId.replace) {
                var ids = require('../metadata/ids.json');
                if(ids[chunkId]) {
                  var chunkPath = './' + ids[chunkId].replace(/^\\.[\\\\/]/, '') + '.js';
                  chunk = require(chunkPath);
                } else {
                  var chunkPath = './' + chunkId + '.js';
                  chunk = require(chunkPath);
                }
                
              } else {
                var chunkPath = './' + chunkId.replace(/^\\.[\\\\/]/, '') + '.js';
                chunk = require(chunkPath);
              }
              
              var moreModules = chunk.modules, chunkIds = chunk.ids;

              for(var moduleId in moreModules) {
                modules[moduleId] = moreModules[moduleId];
              }
              for(var i = 0; i < chunkIds.length; i++)
                installedChunks[chunkIds[i]] = 0;
              }
          return require('@iherb-react-environment/components').SameLoopPromise.resolve();`;

          return updatedCode;
        },
      );
    });
  }
}
