"use strict";
exports.__esModule = true;
// This plugin modifies the require-ensure code generated by Webpack
// to work with Next.js SSR
var NextJsSsrImportPlugin = /** @class */ (function () {
    function NextJsSsrImportPlugin() {
    }
    NextJsSsrImportPlugin.prototype.apply = function (compiler) {
        compiler.hooks.compilation.tap("DynamicImportPlugin", function (compilation) {
            compilation.mainTemplate.hooks.requireEnsure.tap("DynamicImport", function (code, chunk) {
                var updatedCode = "\n          if(installedChunks[chunkId] !== 0) {\n              var chunk;\n\n              if(!chunkId.replace) {\n                var ids = require('../metadata/ids.json');\n                if(ids[chunkId]) {\n                  var chunkPath = './' + ids[chunkId].replace(/^\\.[\\\\/]/, '') + '.js';\n                  chunk = require(chunkPath);\n                } else {\n                  var chunkPath = './' + chunkId + '.js';\n                  chunk = require(chunkPath);\n                }\n                \n              } else {\n                var chunkPath = './' + chunkId.replace(/^\\.[\\\\/]/, '') + '.js';\n                chunk = require(chunkPath);\n              }\n              \n              var moreModules = chunk.modules, chunkIds = chunk.ids;\n\n              for(var moduleId in moreModules) {\n                modules[moduleId] = moreModules[moduleId];\n              }\n              for(var i = 0; i < chunkIds.length; i++)\n                installedChunks[chunkIds[i]] = 0;\n              }\n          return require('@iherb-react-environment/components').SameLoopPromise.resolve();";
                return updatedCode;
            });
        });
    };
    return NextJsSsrImportPlugin;
}());
exports["default"] = NextJsSsrImportPlugin;
//# sourceMappingURL=import-plugin.js.map